### ISSUE TITLE
A specification project may also be "created" by Restructuring Review

### ISSUE THREAD

**Issue by waynebeaton** [EclipseFdn/EFSP#11]
If a new project is truly being created, then the Restructuring Review can be combined with a Creation Review. Nothing to see here.

If an existing project is being changed into a Specification Project, then nothing new is being created. Instead, the nature of an existing project is being changed. I don't believe that the EFSP is strictly at odds with this, but there may be a hole with regard to the Specification Committee approval of the "creation".

**Comment by bshannon** [comment]
If an existing project is changed to a spec project, an EDP Creation Review may not be
required, but a spec committee approval definitely must be required.

And likely this would involved a change of scope for the project.  Does a scope change
not require an EDP Restructuring Review?

**Comment by waynebeaton** [comment]
I've added this content to the _Creation Review_ section:

> An existing Project may be converted into a Specification Project via a Restructuring Review. In this case, the Restructuring Review serves as the Creation Review; other changes to the nature of the existing Project (e.g., the Scope) may be included with the Restructuring Review. Unlike a Creation Review, no Project Proposal is required for a Restructuring Review. Like a Creation Review, a Restructuring Review that converts an existing Project into a Specification Project must be approved by the Specification Committee by Super-majority ballot. 

> If an existing project is changed to a spec project, an EDP Creation Review may not be
> required, but a spec committee approval definitely must be required.

Definitely.

> And likely this would involved a change of scope for the project. Does a scope change
> not require an EDP Restructuring Review?

Yes. Yes it does.
