### ISSUE TITLE
Make the means by which exceptions are granted explicit

### ISSUE THREAD

**Issue by waynebeaton** [EclipseFdn/EFSP#12]
We'll add an "Exceptions" section that states that exceptions to the process may be granted at the sole discretion of the Eclipse Foundation Executive Director based on a recommendation from the Working Group's Specification Committee.

**Comment by waynebeaton** [comment]
Exceptions are a big deal. I'm thinking that unanimous approval from the Specification Committee is required. So... something along the lines of:

> Exceptions to this process may be granted only with unanimous approval of the Specification Committee and Executive Director. All exceptions must be documented as part of the public record.

Or something to that effect.

What do you think @mmilinkov and @bshannon?

**Comment by bshannon** [comment]
Exceptions are a big deal.  Does "unanimous" mean everyone has to vote?
Everyone has to vote "+1"?  Or just that no one has voted "-1"?

**Comment by waynebeaton** [comment]
A super majority vote is called for to grant exceptions. The notion of super majority vote is well defined.
