### ISSUE TITLE
Revise the default length for all review periods.

### ISSUE THREAD

**Issue by waynebeaton** [EclipseFdn/EFSP#14]
Add the following:

1. Unless otherwise stated in a specialization of the EFSP, the default length for all review periods is 14 days. During that time, any member of a specification committee can request an extension of the review period to 30 days to permit them additional time for intellectual property reviews.
2. No Review period can be shorter than 7 days, and no specialization of the EFSP is permitted to reduce the review period to less than 7 days.

**Comment by waynebeaton** [comment]
I believe that the right place to add this is in the Specification Committee/Approvals section.

I propose that we add an approval "catch-all" phrase to provide guidance on how to make decisions when the process is silent. e.g., something along the lines of:

> Unless otherwise stated in this document or documented in writing by the Specification Committee, Super-majority approval is required for all decisions related to the development of specifications under this process.

Or something to that effect.

I'd like to revise the wording and structure that was initially proposed.

> Unless otherwise stated in this document or documented in writing by a Specification Committee, the default length for all Specification Committee ballots is fourteen (14) days. During that time, any member of a Specification Committee may request that the period be extended to thirty (30) days to permit them additional time for intellectual property reviews.
>
> No ballot period can be shorter than seven (7) days. A Specification Committee may opt to increase the length of the ballot period, but cannot--under any circumstances--reduce any review period to fewer than seven (7) days.

In #12, I am going to propose that exceptions to the process be granted only with unanimous approval of the Specification Committee and Executive Director. I believe that this may be considered at odds with "under any circumstances" above.

Is this close? @mmilinkov @bshannon

**Comment by bshannon** [comment]
Some uses of "can" should probably be "may".

You might need a "notwithstanding" in that last section.

I'm not sure "documented in writing" is sufficient.  Don't we want changes to the default to be
in a customization of the EFSP?

I suppose this would allow a customization to set a default of 21 days, shortened by a role of dice,
or lengthened to the next full moon.  The only absolute limit is a minimum of 7 days, right?

**Comment by waynebeaton** [comment]
> Some uses of "can" should probably be "may".

Agreed.

> You might need a "notwithstanding" in that last section.

Can you be specific?

> I'm not sure "documented in writing" is sufficient. Don't we want changes to the default to be
> in a customization of the EFSP?

I'm going to yank out "documented in writing". I think that it adds more confusion than it relieves. The statement in the preamble, "... individual Specification Committees may tailor the process for their unique requirements" gives us the coverage that we need.

> I suppose this would allow a customization to set a default of 21 days, shortened by a role of dice,
> or lengthened to the next full moon. 

Only when it's not a leap year.

> The only absolute limit is a minimum of 7 days, right?

Right.

**Comment by bshannon** [comment]
"Notwithstanding the section that describes how exceptions are authorized, no ballot period can be shorter than seven (7) days."

Just something to make it super-clear that no exceptions can be made to this rule.

**Comment by waynebeaton** [comment]
This feels like something that should be more tightly coupled with the Exceptions section.

I've added the following to the end of that section.

> Notwithstanding this exception process, no Specification Committee ballot period may be shorter than seven (7) days.
