### ISSUE TITLE
Clarify the nature of "early adopters"

### ISSUE THREAD

**Issue by waynebeaton** [EclipseFdn/EFSP#17]
There is some potential for confusion regarding who we describe as "early adopters".

Per @bshanon in #15, 

> I think of the people *using* the non-final implementations as the early adopters. The people building the implementations are just the implementors.  I don't classify them as "early" or "late".

It is intended that the "early adopters" are implementors.

**Comment by waynebeaton** [comment]
The document describes milestones as being intended for "distribution to key stakeholders to solicit feedback" in a couple of places. I'm thinking that we pull the content from one of these places and insert it as a replacement for the second sentence in the first paragraph of the _Milestone Builds_ section.

> Leading up to a Release, a Specification Team must produce at least one Milestone Build. <strike>Milestone Builds and Release Candidates are "almost Releases" intended for adoption and testing by early-adopters</strike>**Milestones Builds should be staged for limited distribution to key stakeholders to solicit feedback.** No formal Reviews are required for Milestone Builds.

**Comment by waynebeaton** [comment]
I've updated this in d6c06dfae3532861f3425d50f488a5bcb7ac476d.

**Comment by starksm64** [comment]
It is not practical to have staging for limited distribution in general. The Jakarta staging repo simply has too limited a lifespan for a given release, and so the build will have to be available via a public repository or website. Any limiting of distribution is an archaic notion that stems from earlier JCP days where code as not open source and TCKs were private. All you can say about a milestone release is that a compatible implementation cannot be based off of it.
