### ISSUE TITLE
The handling of optional elements of a specification needs clarification

### ISSUE THREAD

**Issue by starksm64** [EclipseFdn/EFSP#22]
Clarification as to whether a single compatible implementation must implement ALL optional specification aspects is a requirement, or that one or more compatible implementations in union are required to cover all optional specification aspects is needed.

**Comment by waynebeaton** [comment]
I believe that I've created a duplicate with #42.

My solution there was to remove any discussion of it entirely as I don't believe that it should be the place of the specification process to prescribe the nature of the specifications themselves. As I commented on that issue, I believe that we should leave this up to individual specification committees to decide whether or not the added restriction is required. You'll note that I've applied similar logic to supersetting.

Does that work for you, @starksm64? If yes, please close this issue and add any follow up discussion on #42.

**Comment by starksm64** [comment]
Yes, as long as the requirements around optional are removed we can sort out related scope issues in #42.
