### ISSUE TITLE
Remove Service Releases from the Approvals section of EFSP

### ISSUE THREAD

**Issue by kwsutter** [EclipseFdn/EFSP#29]
The Jakarta EE Specification Committee was attempting to clarify how to process Service Releases for Specifications.  This was being done via the following two PRs:

JESP Update:  https://github.com/jakartaee/jakarta.ee/pull/1050
Ops Guide Update:  https://github.com/jakartaee/jakarta.ee/pull/1047  

In the [JESP Update PR](https://github.com/jakartaee/jakarta.ee/pull/1050), it was pointed out by Wayne that the [Approvals section of the EFSP](https://github.com/EclipseFdn/EFSP/blob/master/source/process.adoc#approvals) indicates that a Super Majority Vote is required for Service Releases.

But, in the [Specification Version LIfecycle section of the EFSP](https://github.com/EclipseFdn/EFSP/blob/master/source/process.adoc#specification-version-lifecycle), the first sentence indicates that the lifecycle as defined does not apply to Service Releases:
_`To produce a Specification Version (with the exception of Service Releases) a Specification Team must engage in a formal Release Cycle under the supervision of the Project Management Committee (PMC) and the Specification Committee.`_

Also, in the [Service Release section of the EFSP](https://github.com/EclipseFdn/EFSP/blob/master/source/process.adoc#service-releases), there is this confusing statement:
_`A Specification Team must have engaged in a successful Release Review for a Major or Minor Release prior to engaging in a Service Release. No Progress Review is required for a Service Release; the Specification Team must, however, engage in a successful Release Review.`_

This section is what we were attempting to clarify and simplify via the [JESP Update PR](https://github.com/jakartaee/jakarta.ee/pull/1050).

Our interpretation of these inconsistencies is that the "Service Release" reference in the Approvals section was a mistake.  If Service Releases have to follow the exact same, detailed process as the other type of releases, then why did we insert these "exception" clauses in those two other sections?

Also, there are examples of producing Service Releases without such a formal process.  We have produced Service Releases for both TCKs and APIs for Jakarta EE.  And, since the APIs contain Javadoc, which is considered part of the "Specification", then we already have a simpler process being used to produce Service Releases for Specifications.  We just don't have it properly documented.

We need to quickly come to a conclusion on this interpretation since these Service Releases are coming into play for Jakarta EE 9.1.  We are aware of at least four Spec Projects which want to correct their Javadoc for 9.1 via Service Releases for their respective API artifacts.  The overall Release Plan for 9.1 is targeted for end of January, so we need to resolve this definition quickly.  Even if we can't get the EFSP updated and published, if we can get agreement on the direction so that we can make progress with 9.1, that would be appreciated.

**Comment by kwsutter** [comment]
I should also point out that once Wayne saw our proposed direction for the JESP Update, he created Issue #27.  But, his take was that a Service Release should adhere to the same process as the other types of releases.  So, we have a disconnect and, thus, this separate Issue.

**Comment by dblevins** [comment]
Thanks for opening this, @kwsutter !

My recollections of the discussions we had while creating the EFSP match what you detail here.  We defined a clear Release Review process that did involve a minimum 7-day voting period and super-majority vote.  We did feel that was too much overhead for situations that are minor corrections of the specification and wanted a lighter version of the process we could leverage for non-functional issues in spec (pdf or javadoc) such as typos, formatting issues, etc and update exclude lists.   The JCP process has such a concept with maintenance releases which we discussed.  The motivation for adding the Service Release definition was to address that need without having to incur the full Release Review.

We also discussed that we couldn't actually use that for Jakarta EE 8 even though we were not changing the functionality of the specifications or TCKs as we hadn't yet released them through any Eclipse process including the in-progress-EFSP.  So we clarified the definition of Service Release to explicitly call out it cannot be used for such scenarios -- you cannot issue a Service Release for something that has never gone through a full Release Review.  The intent was once you've done that at least once, you can go ahead and issue Service Releases in the future.  Again, Service Releases are not to include any change in behavior in the specification itself.

It wasn't our intent to go through the effort of carving out this use case only to still and always mandate a Release Review.  It is, however, very understandable the intent was muddied as we immediately hit an edge case that filled it with caveats that can confuse the matter.

I'll add that though Service Release says "only minor changes" are allowed our intent was actually no changes in behavior. Typos, formatting, clarifying a sentence, updating excludes in tck, etc are all fine.  With "minor" being heavily open to interpretation I recommend we expand that to use the phrasing that is already in the description of what is allowed to be changed *during* a vote.  There we say:

> All artifacts related to a ballot ... must not change during the ballot period (with the exception of minor corrections that do not change the semantic intent....

If we take that key phrase of "do not change the semantic intent" and add it to the definition of Service Release I think we'd get to something on target to what we were expecting and less open to misinterpretation.  Maybe something like:

> A Service Release includes only minor changes and/or clarifications over a Major or Minor Release that do not change the semantic intent or behavior.

**Comment by waynebeaton** [comment]
The document is consistent. It may be confusing, but it is consistent.

> To produce a Specification Version (with the exception of Service Releases) a Specification Team must engage in a formal Release **Cycle** under the supervision of the Project Management Committee (PMC) and the Specification Committee.

The section goes on to describe a "Release Cycle" as starting with a plan review, and may include progress reviews. The exception is that service releases don't require a plan review or any progress reviews, just a Release **Review** and successful ballot (i.e., only the very last part of the release cycle).

I'll accept an argument that we an opportunity to make this easier to parse.

The EFSP 1.0 required just a successful ballot of the specification committee for service releases. We actually _strengthened_ the requirement to a full release review with version 1.1 (see Issue #10). The change to require a full release review was included in the diff to the Jakarta EE Specification Committee on [March 6/2019](https://jakarta.ee/meeting_minutes/specification_committee/minutes-specification-march-6-2019.pdf). Note that the "GitHub" link in the notes doesn't work anymore. The [Git log](https://github.com/EclipseFdn/EFSP/compare/1.0...version_1_1) nonetheless records the differences as they would have been presented at that time.

I believe that the Eclipse Foundation's IP Policy requires the release review for service releases of specification projects. I can research this further if we decide to pursue this.

In the meantime, to solve your immediate problem, I recommend that you initiate a _single_ ballot for the service release for all specifications immediately (there's no rule that governs the exact nature of ballots, you can just do one). I can schedule a single out-of-cycle release review for all projects and do an informal IP Log review (i.e., don't submit IP Logs).

**Comment by waynebeaton** [comment]
I've opened an issue to consider formalizing the notion of Errata. See #32.

**Comment by andymc12** [comment]
I've brought up a similar issue (the painfulness of a micro/service/patch release) in the MicroProfile mail list at https://groups.google.com/u/1/g/microprofile/c/ZC-ZrPM80fQ and @sutter referred me here.  I'm definitely looking forward to a resolution to this issue - and a simpler overall process for micro releases (where only fixing spec/javadoc wording, TCK tweaks, etc.).

**Comment by waynebeaton** [comment]
> I've opened an issue to consider formalizing the notion of Errata. See #32.

To be clear, I opened this issue as a means of discussing an alternative (or perhaps complementary) solution, not as an additional type of release.

**Comment by waynebeaton** [comment]
IMHO, the Eclipse Foundation's IP Policy supports a notion of a release without ceremony (i.e., no review) so long as that release does not implicate any additional intellectual property.

That is, I believe that we can make this change so long as we can provide some reasonable guardrails around the definition of "service release". As I stated in #32, my thinking is that a service release cannot break a compatible implementation that has already passed the TCK (i.e., a subsequent run of the TCK should pass on a compatible implementation that has already certified).

I'm thinking that we need to further refine our definition of "service release" to clarify that "minor changes and/or clarifications" must not implicate additional intellectual property (i.e., the changes cannot read on any additional patents, so additional patent grants are not required, so a review to lock in additional patent grants is not required). 

The EFSP currently states:

> A Specification Team may consult with their PMC and Specification Committee to determine precisely what constitutes a minor change and/or clarification.

This statement, I believe, is sufficient to encourage the specification committee to provide specific guidance regarding what does and does not constitute a service release.

The EFSP currently states:

>  The Specification Committee may, at their discretion, demand that the project team engage in additional Progress Reviews.

This statement, I believe, grants the specification committee sufficient power to compel a project to engage in a review to lock in patent grants for a service release should they detect that shenanigans are afoot.

**Comment by waynebeaton** [comment]
I've closed #25 as `wontfix`. 

A pull request to address this issue is coming.
