### ISSUE TITLE
Specify the minimum duration for specification committee votes

### ISSUE THREAD

**Issue by waynebeaton** [EclipseFdn/EFSP#3]
Version 1.0 does states only that a super-majority vote is required. It does not specify how a vote is undertaken.

We discussed today that we should add:

* Minimum 14 days voting for progress, release, and service release votes;
* Minimum 7 days voting for plan and creation approval.

We reasoned that progress, release, and service release votes have implications regarding intellectual property and so will require more time for legal review. Planning and creation votes do not have direct intellectual property implications and so can default to standard seven day period that we use for everything else.

Theoretically, a service release vote that does not have IP implications could be shorter, but it may be difficult to consistently determine whether or not a service releases has IP implications.

We may consider adding a "notwithstanding clause" that gives the specification committee the ability to override the standard voting minimums under special circumstances. 

The specification committee should also be able to reset the clock or otherwise move a vote deadline to give project teams an opportunity to resolve issues before a vote concludes.

**Comment by waynebeaton** [comment]
The EFSP lists the following lifecycle events that require a vote (annotated with the period of time that were suggested on the last call).

* The creation of a new Specification Project. **7 days**
* The Release Plan for a new Release Cycle of a Specification. **7 days**
* Each revision to the Scope of a Specification.
* Each Review of a Specification Project, including the adoption of Specification Versions. **14 days**
* A Profile Specification (this Super-majority must include a Super-majority of Strategic Members).
* A Platform designation (this Super-majority must include a Super-majority of Strategic Members).
* Service Releases. **14 days**

I'm thinking that scope changes are a 14 day vote and that everything else is 7 days.

**Comment by bshannon** [comment]
So you're proposing to change all the "14 days" above to "7 days", and add "14 days" to the third bullet, and add "7 days" to the 5th and 6th bullets?

I definitely agree with making Service Releases 7 days.

I assume scope changes are relatively rare, so the time may not matter.

If changing the scope of a project requires 14 days, then I think the initial creation of the project should require 14 days as well.

I can imagine that the votes requiring a super-majority might thus require more time for the Strategic Members to consider how to vote.

**Comment by waynebeaton** [comment]
I'm questioning the 14 day requirements.

As I recall, 14 days was suggested as a reasonable minimum amount of time to allow the representatives on the specification committee to connect with their legal teams.

A specification project must go through a minimum of three specification committee votes for each development cycle (each specification version must start with either a creation review or plan review, engage in at least one progress review, and finish with a release review). According to the Eclipse IP Policy, the progress review is the first point in the release cycle at which intellectual property grants are locked in (plan reviews are not considered a "checkpoint review"). So, the specification committee already has the time between the plan (or creation) review and the progress review to consult with their legal team (and field concerns from specification project participants about their essential claims). 

The only real timing concern, I think, is that we give specification committee members a reasonable chance to vote. In practice, we've found that one week (splitting the week, e.g. Thursday to Wednesday) is a reasonable minimum amount of time for a vote.

Of course, individual specification committees can opt to increase the minimum

Do we really need to bake a 14 day minimum for these sorts of vote?

**Comment by bshannon** [comment]
Legal can't review the IP issues until the spec stops changing.  So while there's plenty
of time between creation and progress reviews, the spec is changing during that time.

**Comment by waynebeaton** [comment]
How does this manifest in practice?
e.g. is it common for EC members in the JCP to consult with their legal teams before voting?

Essential claims are locked in by participation in the specification. A specification committee representative could theoretically vote no on a progress or release review that passes, locking in the IP from that representative's organization by virtue of that organization having a committer on the specification project.

In this context, the specification committee's vote is primarily about confirming that the content under review is within the agreed-to scope. If an organization wants to pull their IP, they'd have to pull their committers before the start of a review.

**Comment by bshannon** [comment]
They'd have to pull their committers before the *completion* of the review.

If you've ever dealt with lawyers you know they work on worst case scenarios.
In the worst case, legal may need to be consulted, and 7 days seems too short
for that.

As discussed in today's meeting, making the minimum 14 days in the JESP is
sufficient for now.  Likely Oracle would want that to be the case for every working
group specification process it was involved in.  If there are other companies who
think 7 days is sufficient and want to work on a separate specification process that
Oracle would not be involved in, that's fine.

**Comment by waynebeaton** [comment]
With commit bcc46f16efc74e784e7764baf7150d5582780bf9, I've added that specification committee votes must be scheduled to run for a minimum of one week. Individual working groups may increase this number for any subset of the votes as required/desired.
