### ISSUE TITLE
 Eclipse Foundation Specification Process image update is needed for Plan 

### ISSUE THREAD

**Issue by TanjaObradovic** [EclipseFdn/EFSP#37]
On the https://www.eclipse.org/projects/efsp/#efsp-version-lifecycle, image "An overview of the Eclipse Foundation Specification Process", the expectation is that Proposal, Plan, Milestone, SpecVersion and Ratified Final Specification all would be represented in oval-ish element, but Plan is not. Can we fix that?

Thanks,
Tanja

**Comment by waynebeaton** [comment]
I believe that I was originally thinking of "Plan" as a verb. As in, "Plan the next release". You're interpreting it as "Plan" being a noun, as in the output of the planning activity. I think that both work in this diagram.

So, you're thinking that we change it to this, right?

![image](https://user-images.githubusercontent.com/555569/114192044-0ca15b00-991b-11eb-857a-2d51ede77872.png)

**Comment by TanjaObradovic** [comment]
Yes, that is what I was thinking of. Thanks!

**Comment by waynebeaton** [comment]
If we maybe try too hard, we can represent both the planning and the plan.

![image](https://user-images.githubusercontent.com/555569/114193725-cea53680-991c-11eb-9429-1378655d56af.png)

But I think that this makes the diagram just a bit too complicated.

**Comment by TanjaObradovic** [comment]
I am not sure "Planning" is necessary, I do prefer having the "Plan" only as an artifact.

**Comment by waynebeaton** [comment]
Okay. Let's go with just turning "Plan" into a noun.
