### ISSUE TITLE
Be less prescriptive about the nature of specifications and related artifacts.

### ISSUE THREAD

**Issue by waynebeaton** [EclipseFdn/EFSP#42]
Be less prescriptive about the nature of specifications themselves and related artifacts (e.g., the nature of APIs and TCKs).

For example:

> A Specification may describe parts as being optional. Optional parts of a Specification must not conflict with one another; it must be possible for a Compatible Implementation to implement all optional parts.

This is the sort of requirement that individual working groups specification committees should impose when it makes sense for them to do so.

My thinking for now is that we completely yank this sort of content out of the EFSP and add it (in one form or another) to the operations guide as examples of the sorts of requirements that specification committees can impose over the process via the own specialization of the process.

**Comment by waynebeaton** [comment]
The requirement that the "must not extend the API (no supersetting)" is, I believe, intended to avoid a condition where an API, specifically, a Java interface, is extended in such a way that it is incompatible. If I'm correct, then it should suffice to say that "A Compatible Implementation must fully implement all non-optional elements of a Specification Version<strike>, must not extend the API (no supersetting),</strike> and must fulfill all the requirements of the corresponding TCK."; an implementation that extends a Java interface in an incompatible manner would automatically fail the TCK.

In any case, an individual working group can choose to add this back as an extra requirement for their specialization of the EFSP.

Does this make sense @kwsutter and @edbrat?

**Comment by bjhargrave** [comment]
I am in favor of removing prescriptive language from the EFSP regarding the treatment of optional parts of the specification with respect to one Compatible Implementation. In particular:

> A Specification Version must identify at least one Compatible Implementation under an Open Source License that implements all optional elements of the Specification and fulfills the requirements of all elements (including optional elements) of the TCK.

This imposes an undue burden on possible Compatible Implementations.

> The Specification Team must provide evidence that cited Compatible Implementations fulfill all requirements of the TCK **and that at least one Compatible Implementation implements all optional aspects**.

The latter part of this sentence is another instance of this same burden.

If this concern if not properly part of this issue, then perhaps it is a better fit in #22?

**Comment by mmilinkov** [comment]
> The requirement that the "must not extend the API (no supersetting)" is, I believe, intended to avoid a condition where an API, specifically, a Java interface, is extended in such a way that it is incompatible. If I'm correct, then it should suffice to say that "A Compatible Implementation must fully implement all non-optional elements of a Specification Version, must not extend the API (no supersetting), and must fulfill all the requirements of the corresponding TCK."; an implementation that extends a Java interface in an incompatible manner would automatically fail the TCK.

I think the intent of the "no supersetting" rule is different than what you're suggesting. Without this rule an implementation would be free to add API elements to the (say) jakarta namespace without participating in the specification process. Isn't it the intent of the EFSP that the namespace be tightly controlled? How would a consumer know which jakarta namespace elements came from the spec and which were added by the implementer? 

Or are you saying that we should simply delegate enforcement to the TCK and not have it in the process?

**Comment by bjhargrave** [comment]
The OSGi spec drafts say that an implementation:

> must not modify, subset, superset or otherwise extend the OSGi Name Space, or include any public or protected packages, classes, Java interfaces, fields or methods within the OSGi Name Space other than those required and authorized by the Specification.

This is about stating that only the specification project may change the specification's API and not any purported implementation. This is wholly unrelated to optional parts of a specification. API control and optional specification elements are different things.

> Or are you saying that we should simply delegate enforcement to the TCK and not have it in the process?

I don't think the process needs to prescribe API control (although I am sure most specifications will require this). The specification itself needs to define the requirements for API control (as we do in the OSGi specification) and then TCKs can enforce it.

**Comment by waynebeaton** [comment]
> If this concern if not properly part of this issue, then perhaps it is a better fit in #22?

My strong preference is to delegate concerns the concerns regarding optional elements to the specifications themselves or to the specification committees (e.g., the Jakarta EE working group could decide to include this concept in the JESP).

That is, I think that we should just remove any discussion of optional elements, rendering the request to clarify in #22 moot.

**Comment by waynebeaton** [comment]
> I think the intent of the "no supersetting" rule is different than what you're suggesting. Without this rule an implementation would be free to add API elements to the (say) jakarta namespace without participating in the specification process. Isn't it the intent of the EFSP that the namespace be tightly controlled? How would a consumer know which jakarta namespace elements came from the spec and which were added by the implementer?

I agree with this. I'm not sure how to enforce it with a TCK, but I agree with it. I'll back out that change.

**Comment by bjhargrave** [comment]
> I'm not sure how to enforce it with a TCK, but I agree with it. I'll back out that change.

TCKs often have tests for API subsetting/supersetting. Like optional elements, defining whether a specification's API can be subset/superset should be defined by the specification not by the process.

**Comment by edbratt** [comment]
The Jakarta EE TCKs generally use signature tests to verify this requirement. As stated above, the Spec. project is in charge.

**Comment by waynebeaton** [comment]
Great. It sounds like we're in agreement that we can remove the prohibition of supersetting from the specification process and leave it to individual working groups and specifications to make that requirement.

**Comment by kwsutter** [comment]
> Great. It sounds like we're in agreement that we can remove the prohibition of supersetting from the specification process and leave it to individual working groups and specifications to make that requirement.

@waynebeaton Sorry, didn't realize this was being discussed until now...  Even though Jakarta EE may have signature tests that would catch this, other projects may not (MicroProfile for one).  I think removing this requirement opens the door for inconsistency across API "implementations" across specification projects.  Allowing supersetting of APIs sets a bad precedence (imho).  And, leaving it to individual Spec Projects could be "too late".  That is, Spec Projects may not realize that they need to nail this down with signature tests until it's too late...

**Comment by bjhargrave** [comment]
>  I think removing this requirement opens the door for inconsistency across API "implementations" across specification projects.

Removing this from the EFSP does not prevent a WG's Specification Committee from imposing an equivalent requirement on all the specifications it manages. It is important that things be managed at the proper level, and for this item, it should be managed at the WG level and not the EF level. 

For example, the OSGi WG imposes this requirement on the OSGi specifications. The Jakarta EE WG can impose this requirement on all of the Jakarta specifications.
