### ISSUE TITLE
Compatible Implementations should be defined in terms of a Final Specification

### ISSUE THREAD

**Issue by waynebeaton** [EclipseFdn/EFSP#45]
The definition of _Compatible Implementation_ is, I think, incorrect.

> A Compatible Implementation must fully implement all non-optional elements of a **Specification Version**, must not extend the API (no supersetting), and must fulfill all the requirements of the corresponding TCK. ...

Compatible Implementations must be based on a _Final Specification_.

Note that, with #42, I expect that we're yanking out the requirements regarding non-optional elements, so I'm thinking that we change this to:

> A Compatible Implementation must fulfill all requirements of a Final Specification including all requirements of the corresponding TCK, and must not extend the API (no supersetting). ...

**Comment by bjhargrave** [comment]
As part of this, you also need to improve the text around _candidate_ compatible implementations in a Specification Version. Since a Specification Version (which include a TCK) is not a Final Specification, there can, by definition, be no Compatible Implementations of the Specification Version. Once the Specification Version is Ratified, then it becomes a Final Specification and the submitted _candidate_ compatible implementations become Compatible Implementations.

![image](https://user-images.githubusercontent.com/277682/118186112-5645ff80-b40b-11eb-9b78-731cbe2517e9.png)

![image](https://user-images.githubusercontent.com/277682/118186034-3ca4b800-b40b-11eb-84b5-d506ab527e85.png)

**Comment by starksm64** [comment]
This statement:

> A Compatible Implementation must fulfill all requirements of a Final Specification including all requirements of the corresponding TCK, and must not extend the API (no supersetting). ...

needs to be clarified with regard to extension and supersetting. We are still discussing the optional aspects of specifications, and one of the arguments in favor of being able to drop optional features is that vendors are in fact free to offer these as enhancements outside of the specification. They can be from previous specifications or even specifications that layer on top of the specification in question. An example from JMS discussions included the notions of durability, ordering, guaranteed delivery, etc. as features that may need to be optional. If a base JMS spec described an API that did not support these, a vendor still should be able to provide those features.

**Comment by bjhargrave** [comment]
> needs to be clarified with regard to extension and supersetting

I think the topic here is about adding members to API types or types to API packages. That is, only the specification project is permitted to modify the API. Implementations are free to add other features but cannot directly modify the specified API by adding(supersetting) or removing (subsetting) members and types in the API packages. 

See <https://osgi.github.io/osgi/cmpn/preface.html#d0e56> for the text in the OSGi specifications regarding this.

**Comment by starksm64** [comment]
Right, but one way to deal with optional features is to move them into a new superset spec that adds the features, which may result in modifications to the API. If this is done in a binary compatible way, it should be allowed.

**Comment by bjhargrave** [comment]
> optional features is to move them into a new superset spec

Yes, but that is still a specification controlled by the specification project. I don't think you ever want to let a random specification implementor modify the API. This is why we have signature tests.

**Comment by starksm64** [comment]
Ack.

We already have a potential problem with a need to expand the signature tests to allow for the use case where a new web profile is released that includes config 1.1 for example, while the core profile uses config 1.0. An implementation that wants to certify on both will ship a config 1.1 implementation. How does this work with the signature tests?

If a specification project splits what were optional features into a profile spec and a non-profile spec, they should be able to craft the signature tests to allow for implementations that include the optional features if they are binary compatible with the profile based spec. To date the signature tests have not been this sophisticated.

**Comment by scottmarlow** [comment]
As mentioned above with the current EE TCK signature test tooling, the core profile signature tests will expect the exact config 1.0 api and fail due to the config 1.1 api additions.  

Some options:
1. Update our TCK tooling to allow super-setting but still do not allow sub-setting.  
2. Handle this operationally in that the core profile signature tests failures are ignored by those reviewing the newer web profile compatibility certification request.

**Comment by waynebeaton** [comment]
After some reflection, my strong preference is to leave it to the specification committee or the specifications themselves to decide what compatibility means and focus the EFSP on the intellectual property management issues. I don't believe that supersetting or a notion of optional features have an impact with regard to intellectual property management in general or essential claims in particular.

I can envision other scenarios where a specification might want to encourage supersetting.

In the current draft (the diff between v1.2 and the draft is [here](https://www.eclipse.org/projects/efsp/diff.php)), I've removed the bits about optional features and supersetting.

![image](https://user-images.githubusercontent.com/555569/123307673-c6f33800-d4f0-11eb-9dfb-77d0f48b4459.png)

**Comment by starksm64** [comment]
Yes, that is good. The fewer details in multiple places the better.
