### ISSUE TITLE
Reference Patent Licenses

### ISSUE THREAD

**Issue by waynebeaton** [EclipseFdn/EFSP#47]
The EFSP should reference the requirement for a specification project (or more likely the specification committee) to select a patent license.

I'm thinking that we add _Patent License_ as a term.

Then, we leverage content from the IP Policy for inclusion in the _Specification Project_ section:

> At the commencement of each Specification Project, such Specification Project will have a specified and documented Scope, and explicitly select whether they will utilize an Implementation Patent License or a Compatible Patent License as defined in the Eclipse Foundation Intellectual Property Policy. The Scope and choice of Patent License must be made known to the Specification Committee in advance of the initiation of the Ballot to create the Specification Project.

We might add some content to the _Specification Committee_ section to describe the specification committee's responsibility to set a policy regarding the choice of Patent Licenses for the projects operating under their purview. This may be a better fit for the operations guide.

Finally, we should add content from Mike's blog post, [On Patents and Specifications](https://eclipse-foundation.blog/2021/05/13/on-patents-and-specifications/) to the operations guide.

**Comment by waynebeaton** [comment]
I've added the following term definition:

> Patent License :: The Patent License that defines how patent grants flow from a Final Specification to an implementer of the specification. The Patent License is either the Implementation Patent License or Compatible Patent License as defined in the {ipPolicyUrl}[Eclipse Foundation IP Policy].

I've added the following to the _Specification Projects_ section.

> The _Patent License_ that defines how patent grants flow from a Final Specification to an implementer of the specification. At the time of creation Specification Project must explicitly state whether it utilizes an _Implementation Patent License_ or a _Compatible Patent License_ as defined in the Eclipse Foundation Intellectual Property Policy. The choice of Patent License must be made known to the Specification Committee in advance of the initiation of the Ballot to create the Specification Project.

This last change leads me to want to describe what a Specification Project _must have_. In particular, I'm thinking that I'd like to explicitly state that the Scope must be well-defined and fall within the scope of the corresponding Top-Level Project (Issue #48).

**Comment by starksm64** [comment]
To me trying to get both the scope and patent license type voted on is not effective. If the scope is fine but the patent license type is not approved, then you have to revote with the alternative patent license type. It also seems like the scope could potentially affect the license type. I would suggest that there is a clear statement of scope and vote for approval of that, followed by either application the working group default, or a vote for a specific patent license type.
