### ISSUE TITLE
The Eclipse Foundation Executive Director must approval all Project Proposals

### ISSUE THREAD

**Issue by waynebeaton** [EclipseFdn/EFSP#62]
The Eclipse Foundation Executive Director (ED) must approval all Project Proposals.

The EMO requests approval from the ED before a Project Proposal is posted for community review.

In the event where a Project Proposal undergoes significant changes during the community review period (e.g., the scope or patent license is changed), the EMO will confirm the ED's approval prior to initiating a creation review.

**Comment by mmilinkov** [comment]
+1
Wayne, This makes good sense to me. I see that you've assigned this to me. What more do you need from me at this time?

**Comment by waynebeaton** [comment]
>  I see that you've assigned this to me. What more do you need from me at this time?

Nope. Just experimenting with workflow. I'll take it from here.
