### ISSUE TITLE
"Specification Team" as a synonym for "Project Team" is unnecessary and potentially confusing

### ISSUE THREAD

**Issue by waynebeaton** [EclipseFdn/EFSP#63]
I believe that "Specification Team" is a synonym for "Project Team", and that including the term is unnecessary and potentially confusing. The EDP makes references to responsibilities of the Project Team which, by definition, extend to specification projects; adding a new term potentially confuses this. Further, the name "Specification Team" suggests that a team working on a specification project is somehow different or distinct from the "Project Team" of committers (it might reasonably be expected that a specification project that manages multiple specifications might somehow be able to organize project committers into specification team subsets which is not what is intended). 

Neither term is, AFAICT, used in the IP Policy, Working Group Process, any of the working group agreements, or other related agreements.

IMHO we should remove the definition of "Specification Team", and change all occurrences of "Specification Team" to "Project Team". We might consider including "Project Team" as a definition, but defer to the EDP (i.e., define by reference); although there is a catch all at the bottom of the "Terms and Definitions" section that states "[o]ther terms used in this document are defined in the EDP".

**Comment by mmilinkov** [comment]
I understand your motivation, but there are other perspectives to consider. 

Specifications are not just open source projects. There could be value in distinguishing the roles of participants in specifications versus committers in projects.

Although there is a wide variety across SDOs, I cannot think of an example where the group of people creating a specification are referred to as a "Project Team". Terms that I am familiar with include expert group, special interest group, committee, technical committee, etc etc. As this is a specification process, having some sort of term to describe the group working on the specification that matches industry norms could be of value.

**Comment by Emily-Jiang** [comment]
Actually, I suggest to use Specification Team instead, because we talk about specification in particular. Project team means a lot of more than spec team in my understanding.

**Comment by waynebeaton** [comment]
@mmilinkov in your mental model, is the Specification Team the Project Team? That is, is "Specification Team" another way to refer to the "Project Team", or does it mean something different? Can I define "Specification Team" in the EFSP in terms of "Project Team" as defined in the EDP?

@Emily-Jiang in your mental model, is the Specification Team a subset of the Project Team? e.g., in the MicroProfile (or OSGi) model, where we have a single Specification Project developing multiple specifications, is there a separate Specification Team --composed of a subset of the Project Team -- for each Specification?

**Comment by Emily-Jiang** [comment]
@waynebeaton we just call it a spec team, which means the team work on MP specs. Projects include spec and no-spec (such as marketing).

**Comment by bjhargrave** [comment]
Specifications are "made" in Eclipse open source projects (under the EDP). So the "team" _is_ the Project Team. I don't see any other team than the Project Team. So it seem confusing and duplicative to have a second term, Specification Team, which refers to the same people as the Project Team.

**Comment by mmilinkov** [comment]
> @mmilinkov in your mental model, is the Specification Team the Project Team? That is, is "Specification Team" another way to refer to the "Project Team", or does it mean something different? Can I define "Specification Team" in the EFSP in terms of "Project Team" as defined in the EDP?

In my mental model Specification Team = Project Team. 
Yes, you could define Specification Team in terms of Project Team.
If there is a consensus that having a second label is counter-productive, I'm not going to stand in the way. I was just pointing out that the naming norms in the spec world can be different. There may also be utility in making it clear that they team is working on a Specification rather than open source code. 
Thanks for listening.

**Comment by bjhargrave** [comment]
> There may also be utility in making it clear that they team is working on a Specification rather than open source code.

The reality is that the team _is_ working on open source code. All the APIs and their documentation exist in an open source project under an open source license. There are constraints on contributions to the open source project to ensure IP capture commensurate with a release from the project being able to be declared a Final Specification. But a Final Specification is basically just a declaration about a release from the open source project.

A Specification Project is a shell wrapped around an Eclipse open source project. The shell defines additional requirements about the inputs to the project and defines additional requirements about the outputs of the project. But of course, anyone is free to take the open source project and use it in any way they wish consistent with the open source license of the project.

**Comment by waynebeaton** [comment]
Based on feedback, I've left _Specification Team_ as a term, but have changed its definition to state that it is a synonym of _Project Team_. I've changed occurrences of the term to _Project Team_ where they occur in the document.

> Specification Team :: A synonym for Project Team (as that term is defined in the EDP). The Project Team may also be referred to as an Expert Group, Special Interest Group, or Technical Committee.

I believe (hope) that this gives us the best of all worlds. I share the concerns that using a new term adds potential for confusion (especially in the case where a specification project produces multiple specifications) when interpreting the EFSP in the context of the EDP. By keeping the term, we give people who are familiar with specification work in other contexts a fighting chance of mapping their understanding to how we do things in open source.

> @waynebeaton we just call it a spec team, which means the team work on MP specs. Projects include spec and no-spec (such as marketing).

The EDP or EFSP define roles for project leads, committers, and mentors. There is no marketing project role. While I might argue that we are all marketers, there is no distinct role formalized in the process. As far as the EDP is concerned, either you're a committer or your not, all committers are considered equal, etc. By extension, if you're a committer on a specification project then you have an equal role to every other committer on a specification project. In essence, if you're on the project team, you're on the specification team.

IMHO, the only reason for us to separate them might be to distinguish between subsets of the project team who do specific work on specifications from those who, for example, take the results of that work through reviews, etc. or subsets of the project team that work on distinct specifications, but I don't see how trying to do that does anything but make describing the process more (and unnecessarily) complicated.

Project Teams self-organize. By extension, Specification Teams self-organize.
